version: '3'

volumes:
  pgdata:

services:
#  app:
#    image:
#      book-rate-app-image
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: app
#    networks:
#      - default
#    ports:
#      - 8080:8080
#    depends_on:
#      - db

  db:
    container_name: db
    image: postgres:13
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_rate
      PGGSSENCMODE: disable
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default