CREATE TABLE USERS
(
    ID            BIGSERIAL PRIMARY KEY,
    USER_NAME     VARCHAR NOT NULL UNIQUE,
    FIRST_NAME    VARCHAR NOT NULL,
    LAST_NAME     VARCHAR NOT NULL,
    EMAIL         VARCHAR NOT NULL,
    HASH_PASSWORD VARCHAR NOT NULL,
    ROLE          VARCHAR NOT NULL DEFAULT 'Customer'
);

CREATE TABLE BOOK
(
    ID        BIGSERIAL PRIMARY KEY,
    TITLE     VARCHAR NOT NULL,
    AUTHOR    VARCHAR NOT NULL,
    RATE      NUMBER  NOT NULL,
    PUSHED_BY BIGINT NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE
);